# Dockerfile

# Use the official Ubuntu 24.04 base image
FROM ubuntu:24.04

# Install apt-utils and net-tools
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y apt-utils net-tools && \
    rm -rf /var/lib/apt/lists/*

# Install other named tools
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y git software-properties-common curl wget openssl gosu openssh-server xemacs21 unzip zip && \
    rm -rf /var/lib/apt/lists/*

# Install mysql
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y mysql-server && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /usr/local/src

RUN mkdir sql

WORKDIR /usr/local/src/sql

COPY ./install.sh install.sh

RUN chmod +x install.sh

COPY ./install.sql install.sql

RUN ( mysqld & ) ; \
    sleep 10 && \
    ./install.sh

RUN rm -fr install.sh install.sql

COPY ./rootpassword p

EXPOSE 3306

WORKDIR /user/local/src

CMD ( mysqld & ) && ( tail -f /dev/null )
