services:

  anontion-coturn:
    container_name: "${TAG_COTURN}"
    build:
      context: "../${BUILD_DIR}"
      dockerfile: "../docker/dockerfile-coturn"
      no_cache: true
    image: "${TAG_PREFIX_COTURN}"
    network_mode: host
    #ports:
    #  - "3478:3478/udp"
    #  - "49152-65535:49152-65535/udp"
