# Dockerfile

# Use the official Ubuntu 24.04 base image
FROM instrumentisto/coturn

WORKDIR /etc

COPY ./turnserver.conf turnserver.conf

## Expose ports
EXPOSE 3478/udp
EXPOSE 49152-65535/udp

CMD ["turnserver", "-c", "/etc/turnserver.conf"]
