services:

  anontion-server:
    container_name: "${TAG_SERVER}"
    build:
      context: "../${BUILD_DIR}"
      dockerfile: "../docker/dockerfile-server"
      no_cache: true
      args:
        ANONTION_DOCKER_GITUSER: "${ANONTION_DOCKER_GIT_USER}"
        TAG_ID: "${TAG_ID_SERVER}"
    image: "${TAG_PREFIX_SERVER}"
    network_mode: host
    #ports:
    #  - "443:443/tcp"
    #  - "12121:22/tcp"

  anontion-asterisk:
    container_name: "${TAG_ASTERISK}"
    depends_on:
      - anontion-server
    build:
      context: "../${BUILD_DIR}"
      dockerfile: "../docker/dockerfile-asterisk"
      no_cache: true
      args:
        ANONTION_DOCKER_GITUSER: "${ANONTION_DOCKER_GIT_USER}"
        ANONTION_DOCKER_BUILD: "${ANONTION_DOCKER_BUILD}"
    image: "${TAG_PREFIX_ASTERISK}"
    network_mode: host
    #ports:
    #  - "5060:5060/tcp"
    #  - "5061:5061/tcp"
    #  - "5060:5060/udp"
    #  - "5061:5061/udp"
    #  - "10000-20000:10000-20000/udp"
