#!/bin/bash

exit 1

echo openssl req -new -newkey rsa:2048 -nodes -keyout anontion.key -out anontion.csr

echo openssl rsa -in anontion.key -pubout -out anontion.pub

<VirtualHost *:443>

    SSLEngine on

    # Path to your private key
    SSLCertificateKeyFile /etc/ssl/private/anontion.key

    # Path to your server certificate
    SSLCertificateFile /etc/ssl/certs/your_domain.crt

    # Path to your intermediate certificates (CA bundle)
    SSLCertificateChainFile /etc/ssl/certs/intermediate.crt

    # Optional: Set the strong Diffie-Hellman group for additional security
    SSLOpenSSLConfCmd DHParameters "/etc/ssl/private/dhparam.pem"

</VirtualHost>

sudo a2enmod ssl

sudo a2ensite default-ssl.conf

sudo apachectl restart

openssl dhparam -out /etc/ssl/private/dhparam.pem 2048

sudo chmod 600 /etc/ssl/private/dhparam.pem

sudo chown root:root /etc/ssl/private/dhparam.pem

sudo apachectl restart
