#!/bin/bash

exit 1

sudo ufw allow 22/tcp
sudo ufw allow 12121/tcp
sudo ufw allow 443/tcp
sudo ufw allow 5060/tcp
sudo ufw allow 5060/udp
sudo ufw allow 5061/tcp
sudo ufw allow 5061/udp
sudo ufw allow 10000:20000/udp
